/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
/**
 *
 * @author wawan
 */
public class Dashboard extends javax.swing.JFrame {
    /**
     * Creates new form Dashboard
     */
   private JFrame activeForm = null;

    public Dashboard() {
        initComponents();
    }

    private void openForm(JFrame newForm) {
        if (activeForm != null) {
            activeForm.dispose(); 
        }
        activeForm = newForm;
        activeForm.setVisible(true);
    }
    
    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemProdi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemMahasiswa = new javax.swing.JMenuItem();
        jMenuItemKRS = new javax.swing.JMenuItem();
        jMenuItemLecturer = new javax.swing.JMenuItem();
        jMenuItemCourse = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItemProdi.setText("Prodi");
        jMenuItemProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProdi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        jMenuItemMahasiswa.setText("Mahasiswa");
        jMenuItemMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMahasiswaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMahasiswa);

        jMenuItemKRS.setText("KRS");
        jMenuItemKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKRSActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemKRS);

        jMenuItemLecturer.setText("Lecturer");
        jMenuItemLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLecturerActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLecturer);

        jMenuItemCourse.setText("Course");
        jMenuItemCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCourseActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCourse);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMahasiswaActionPerformed
        // TODO add your handling code here:
        try {
            openForm(new view.StudentForm());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal membuka Mahasiswa: " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemMahasiswaActionPerformed

    private void jMenuItemProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProdiActionPerformed

    private void jMenuItemLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLecturerActionPerformed
        // TODO add your handling code here:
       openForm(new view.LecturerForm());
    }//GEN-LAST:event_jMenuItemLecturerActionPerformed

    private void jMenuItemCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCourseActionPerformed
        // TODO add your handling code here:
        openForm(new view.CourseForm());
    }//GEN-LAST:event_jMenuItemCourseActionPerformed

    private void jMenuItemKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKRSActionPerformed
        // TODO add your handling code here:
        try {
            openForm(new view.InputNilai());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal membuka KRS: " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemKRSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCourse;
    private javax.swing.JMenuItem jMenuItemKRS;
    private javax.swing.JMenuItem jMenuItemLecturer;
    private javax.swing.JMenuItem jMenuItemMahasiswa;
    private javax.swing.JMenuItem jMenuItemProdi;
    // End of variables declaration//GEN-END:variables
}
