/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LecturerController;
import model.Lecturer;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wawan
 */
public class LecturerForm extends javax.swing.JFrame {
    private final LecturerController lecturerController = new LecturerController();
    private List<Lecturer>           allData            = new java.util.ArrayList<>();
    private int                      currentPage        = 1;
    private static final int         PAGE_SIZE          = 5;
    private String                   selectedNidn       = null;
    
    private static final String[] TABLE_COLUMNS = {"NIDN", "NIK", "Nama", "Keahlian"};
    private static final int COL_NIDN     = 0;
    private static final int COL_NIK      = 1;
    private static final int COL_NAMA     = 2;
    private static final int COL_KEAHLIAN = 3;
    /**
     * Creates new form LecturerForm
     */
    public LecturerForm() {
        initComponents();
        loadLecturerData();
    }
   private void loadLecturerData() {
        try {
            allData     = lecturerController.getAll();
            currentPage = 1;
            displayData();
        } catch (SQLException e) {
            showError("Gagal memuat data: " + e.getMessage());
        }
    }

    private void displayData() {
        DefaultTableModel tableModel = new DefaultTableModel(TABLE_COLUMNS, 0);
        String keyword = jTextFieldPencarian.getText().trim().toLowerCase();
        boolean isSearching = !keyword.isEmpty() && !keyword.equals("pencarian");
 
        if (isSearching) {
            populateSearchResults(tableModel, keyword);
            jLabel2.setText("Hasil Pencarian");
        } else {
            populatePage(tableModel);
            int totalPages = calculateTotalPages(allData.size());
            jLabel2.setText("Halaman " + currentPage + " dari " + totalPages);
        }
 
        jTableDataDosen.setModel(tableModel);
    }
 
    private void populateSearchResults(DefaultTableModel tableModel, String keyword) {
        for (Lecturer lecturer : allData) {
            boolean matchNama = lecturer.getName().toLowerCase().contains(keyword);
            boolean matchNidn = lecturer.getNidn().toLowerCase().contains(keyword);
            if (matchNama || matchNidn) {
                tableModel.addRow(buildRowData(lecturer));
            }
        }
    }
 
    private void populatePage(DefaultTableModel tableModel) {
        int start = (currentPage - 1) * PAGE_SIZE;
        int end   = Math.min(start + PAGE_SIZE, allData.size());
        for (int i = start; i < end; i++) {
            tableModel.addRow(buildRowData(allData.get(i)));
        }
    }
 
    private Object[] buildRowData(Lecturer lecturer) {
        return new Object[]{
            lecturer.getNidn(),
            lecturer.getCardID(),
            lecturer.getName(),
            lecturer.getExpertise()
        };
    }
 
    private int calculateTotalPages(int dataSize) {
        return (dataSize == 0) ? 1 : (int) Math.ceil((double) dataSize / PAGE_SIZE);
    }
 
    private void clearForm() {
        jTextFieldname.setText("");
        jTextFieldexpertise.setText("");
        jTextFieldcardID.setText("");
        jTextFieldnidn.setText("");
        jTextFieldPencarian.setText("Pencarian");
        jTextFieldcardID.setEditable(true);
        selectedNidn = null;
    }
 
    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
 
    private void showInfo(String message) {
        JOptionPane.showMessageDialog(this, message, "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jTextFieldexpertise = new javax.swing.JTextField();
        jTextFieldnidn = new javax.swing.JTextField();
        jTextFieldcardID = new javax.swing.JTextField();
        jButtonBatal = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jTextFieldPencarian = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataDosen = new javax.swing.JTable();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();

        jLabel1.setText("MASTER DOSEN");

        jLabel2.setText("Input Data");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Nama");

        jLabel4.setText("NIDN");

        jLabel5.setText("NIK");

        jLabel6.setText("Keahlian");

        jTextFieldname.setText("Nama");
        jTextFieldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnameActionPerformed(evt);
            }
        });

        jTextFieldexpertise.setText("Keahlian");

        jTextFieldnidn.setText("NIDN");

        jTextFieldcardID.setText("NIK");
        jTextFieldcardID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcardIDActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonDelete.setForeground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldnidn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jTextFieldcardID))
                        .addGap(35, 35, 35)
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSimpan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldexpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldexpertise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldnidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldcardID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonSimpan))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTextFieldPencarian.setText("Pencarian");
        jTextFieldPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPencarianActionPerformed(evt);
            }
        });

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        jTableDataDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDataDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDataDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDataDosen);

        jButtonPrevious.setText("<<Prev");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jButtonNext.setText("Next>>");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCari))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButtonPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNext)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevious)
                    .addComponent(jButtonNext))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnameActionPerformed

    private void jTextFieldcardIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcardIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcardIDActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
         String nama     = jTextFieldname.getText().trim();
        String keahlian = jTextFieldexpertise.getText().trim();
        String nidn     = jTextFieldnidn.getText().trim();
        String nik      = jTextFieldcardID.getText().trim();
 
        if (nama.isEmpty() || keahlian.isEmpty() || nidn.isEmpty() || nik.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        try {
            Lecturer lecturer = new Lecturer(nik, nama, nidn, keahlian);
            lecturerController.saveOrUpdate(lecturer, selectedNidn);
            showInfo("Data Dosen berhasil disimpan!");
            clearForm();
            loadLecturerData();
        } catch (IllegalArgumentException ex) {
            showError(ex.getMessage());
        } catch (SQLException ex) {
            showError("Gagal menyimpan: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        if (currentPage > 1) {
            currentPage--;
            displayData();
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedNidn == null) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
            this, "Yakin hapus Dosen dengan NIDN: " + selectedNidn + "?",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                lecturerController.delete(selectedNidn);
                showInfo("Data Dosen berhasil dihapus!");
                clearForm();
                loadLecturerData();
            } catch (SQLException ex) {
                showError("Gagal menghapus: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jTableDataDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDataDosenMouseClicked
        // TODO add your handling code here:
        int row = jTableDataDosen.getSelectedRow();
        if (row >= 0) {
            selectedNidn = jTableDataDosen.getValueAt(row, COL_NIDN).toString();
            jTextFieldnidn.setText(jTableDataDosen.getValueAt(row, COL_NIDN).toString());
            jTextFieldcardID.setText(jTableDataDosen.getValueAt(row, COL_NIK).toString());
            jTextFieldname.setText(jTableDataDosen.getValueAt(row, COL_NAMA).toString());
            jTextFieldexpertise.setText(jTableDataDosen.getValueAt(row, COL_KEAHLIAN).toString());
            jTextFieldnidn.setEditable(false);
        }
    }//GEN-LAST:event_jTableDataDosenMouseClicked

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        int totalPages = calculateTotalPages(allData.size());
        if (currentPage < totalPages) {
            currentPage++;
            displayData();
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        currentPage = 1;
        displayData();
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jTextFieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPencarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDataDosen;
    private javax.swing.JTextField jTextFieldPencarian;
    private javax.swing.JTextField jTextFieldcardID;
    private javax.swing.JTextField jTextFieldexpertise;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldnidn;
    // End of variables declaration//GEN-END:variables
}
